"""empty message

Revision ID: df65407cc078
Revises: 75e3e38656fc
Create Date: 2025-04-21 14:46:04.427269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df65407cc078'
down_revision = '75e3e38656fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint('email', 'users', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_constraint('email', 'users', type_='unique')
    op.drop_column('users', 'email')

    # with op.batch_alter_table('items', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=sa.Float(precision=2),
    #            type_=sa.REAL(),
    #            existing_nullable=False)

    # ### end Alembic commands ###
   #with op.batch_alter_table('users', schema=None) as batch_op: 
# with op.batch_alter_table('items', schema=None) as batch_op:
#         batch_op.alter_column('price',
#                existing_type=sa.REAL(),
#                type_=sa.Float(precision=2),
#                existing_nullable=False)

#     with op.batch_alter_table('users', schema=None) as batch_op: